### Registrar usuario
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
  "email": "test@datagol.com",
  "password": "123456",
  "rol": "Usuario"
}

### Login usuario
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "email": "test@datagol.com",
  "password": "123456"
}

### Crear equipo
POST http://localhost:3000/api/teams
Content-Type: application/json

{
  "nombre": "Los Pibes FC",
  "ciudad": "Montevideo",
  "categoria": "Libre",
  "entrenador": "Juan Perez"
}

### Obtener todos los equipos
GET http://localhost:3000/api/teams

### Obtener equipo por id
GET http://localhost:3000/api/teams/6a2759cefeb253c232bcf719


### Actualizar equipo
PUT http://localhost:3000/api/teams/6a2759cefeb253c232bcf719
Content-Type: application/json

{
  "nombre": "Los Pibes FC",
  "ciudad": "Buenos Aires",
  "categoria": "Libre",
  "entrenador": "Carlos Gomez"
}